name: build and test

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - name: version
        id: version
        shell: bash
        run: echo "::set-output name=version::$(date +'%Y.%m.%d')"
      - name: cross-compile
        shell: bash
        run: |
          GOOS=linux GOARCH=mipsle go build -compiler gc -o target/udp2http.${{ steps.version.outputs.version }}.linux.mipsle main.go
          GOOS=linux GOARCH=amd64 go build -compiler gc -o target/udp2http.${{ steps.version.outputs.version }}.linux.x64 main.go
          GOOS=darwin GOARCH=amd64 go build -compiler gc -o target/udp2http.${{ steps.version.outputs.version }}.darwin.x64 main.go
      - name: upload platform-specific binaries to artifacts
        uses: actions/upload-artifact@v3
        with:
          path: target/udp2http*
          if-no-files-found: error

  access-binaries:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: download binaries
        uses: actions/download-artifact@v3
        with:
          path: target/bin
      - name: test presence
        run: |
          ls -lah target/bin/artifact
